#! /usr/bin/env python


import getopt
import sys
from gflow.gflow import GFlow
from gflow.config import Config


def parse_options():
    outstream = sys.stdout
    optstr = "h:"
    longopts = ["help"]
    (options, args) = getopt.getopt(sys.argv[1:], optstr, longopts)
    for key, value in options:
        if key in ("-h", "--help"):
            print_usage(outstream)
            sys.exit(0)
        else:
            pass
    configfile = None
    if len(args) > 0:
        configfile = args[0]
        try:
            instream = open(configfile, "r")
        except IOError as e:
            print >> sys.stderr, "ERROR: Cannot output file %s" % configfile
            print >> sys.stderr, e
            sys.exit(1)
    elif not sys.stdin.isatty():
        instream = sys.stdin
    else:
        print >> sys.stderr, "ERROR: Please provide a config file"
        print_usage(sys.stderr)
        sys.exit(1)
    instream.close()
    return configfile

def print_usage(outstream):
    usage = ("Usage: gflow [options] config.txt\n"
             "  Options:\n"
             "    -h|--help           print this help message and exit")
    print >> outstream, usage

if __name__ == '__main__':
    configfile = parse_options()
    options = Config(configfile)
    gflow = GFlow(options)
    gflow.run_workflow()
